### ISSUE TITLE
how  to run pipe4C.R

### ISSUE THREAD

**Issue by liu-555** [deLaatLab/pipe4C#1]
Hi, when I run "Rscript pipe4C.R", it shows as follow:
Error: Package not found: argparse
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘optparse’
Execution halted
Argparse works well in python, I don't konw how to solve it. Could you help me?

**Comment by geertgeeven** [comment]
Hi ! You need to have the optparse R package from CRAN installed on your local R to use the pipe4C pipeline. The 'argparse' error message is a bug, it should read 'optparse', I have fixed this. But please install optparse. To install the last version released on CRAN use the following command:

install.packages("optparse")

Hope this helps !

**Comment by liu-555** [comment]
Thank you very much. I have install the optparse R package. When runing "Rscript pipe4C.R" , a new error message appear.
Error in make_option(c("-nb", "--nonBlind"), action = "store_true", default = FALSE,  : 
  Short flag -nb must only be a '-' and a single letter
Execution halted

**Comment by liu-555** [comment]
> Hi ! You need to have the optparse R package from CRAN installed on your local R to use the pipe4C pipeline. The 'argparse' error message is a bug, it should read 'optparse', I have fixed this. But please install optparse. To install the last version released on CRAN use the following command:
> 
> install.packages("optparse")
> 
> Hope this helps !
Hi, Thank you very much. I have install the optparse R package. When runing "Rscript pipe4C.R" , a new error message appear.
Error in make_option(c("-nb", "--nonBlind"), action = "store_true", default = FALSE, :
Short flag -nb must only be a '-' and a single letter
Execution halted

**Comment by geertgeeven** [comment]
Can you tell us what arguments you are passing on the command line to pipe4C, i.e. can you tell us how you invoke pipe4C from the command line ? And what version of R and what OS are you on ? We will look into it !

**Comment by geertgeeven** [comment]
I have changed the short-flag for the --nonBlind argument to "-i", please note this change. Please pull these changes to your local pipe4C repo and try to run the pipeline again.

**Comment by liu-555** [comment]
(1) I download the latest version of the pipeline from this git repository using:
    **$ wget https://github.com/deLaatLab/pipe4C/archive/master.zip
    $ unzip master.zip
    $ cd ./pipe4C-master**
Then I run the command line:
**/bin/Rscript pipe4C.R --vpFile=./example/VPinfo.txt --fqFolder=./example --outFolder=./outF/ --cores 8 --plot --wig**
### Error in make_option(c("-nb", "--nonBlind"), action = "store_true", default = FALSE,  : 
  Short flag -nb must only be a '-' and a single letter
Execution halted
Then I try to run “/bin/Rscript pipe4C.R”， there‘s the same error.
（2）R version is  R-3.2.4

（3）Linux version 2.6.32-131.0.15.el6.x86_64 (mockbuild@x86-007.build.bos.redhat.com) (gcc version 4.4.4 20100726 (Red Hat 4.4.4-13) (GCC) ) #1 SMP Tue May 10 15:42:40 EDT 2011
We invoke it  follow a step by step tutorial of your newest pipeline. Many thanks for your kindly help. 

> I have changed the short-flag for the --nonBlind argument to "-i", please note this change. Please pull these changes to your local pipe4C repo and try to run the pipeline again.



> I have changed the short-flag for the --nonBlind argument to "-i", please note this change. Please pull these changes to your local pipe4C repo and try to run the pipeline again.

**Comment by geertgeeven** [comment]
It seems you still have the unchanged version. Can you delete the version you have and re-download it once again. Otherwise, download the master.zip from here and extract it again :+1: 
https://drive.google.com/open?id=10bFlsMyhpbD9MsgJhiY6f8Bf9mIP8TLq
The pipe4C.R should no longer have a '-nb' short-flag option, but -i (or --nonBlind) instead

**Comment by liu-555** [comment]
> It seems you still have the unchanged version. Can you delete the version you have and re-download it once again. Otherwise, download the master.zip from here and extract it again 
> https://drive.google.com/open?id=10bFlsMyhpbD9MsgJhiY6f8Bf9mIP8TLq
> The pipe4C.R should no longer have a '-nb' short-flag option, but -i (or --nonBlind) instead
Due to the location I am in, my access to this page have been restricted.

**Comment by liu-555** [comment]
> It seems you still have the unchanged version. Can you delete the version you have and re-download it once again. Otherwise, download the master.zip from here and extract it again 
> https://drive.google.com/open?id=10bFlsMyhpbD9MsgJhiY6f8Bf9mIP8TLq
> The pipe4C.R should no longer have a '-nb' short-flag option, but -i (or --nonBlind) instead


Hi, I  delete the old vision and redownload it use the command line
**$ wget https://github.com/deLaatLab/pipe4C/archive/master.zip
$ unzip master.zip
$ cd ./pipe4C-master**
When I run "/bin/Rscript pipe4C.R" the error is:
**"Usage: pipe4C.R [options]
Values stored in the configuration file (conf.yml) are used by default.
Error: vpFile is required.
Execution halted"**
When I run **/bin/Rscript ./pipe4C.R --vpFile=./example/VPinfo.txt --fqFolder=./example --outFolder=./outF/ --cores 8 --plot –wig**
it shows:
**------ Loading functions and configuration file
Error: Package not found: ShortRead
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘ShortRead’
Execution halted**

**Comment by liu-555** [comment]
> It seems you still have the unchanged version. Can you delete the version you have and re-download it once again. Otherwise, download the master.zip from here and extract it again 
> https://drive.google.com/open?id=10bFlsMyhpbD9MsgJhiY6f8Bf9mIP8TLq
> The pipe4C.R should no longer have a '-nb' short-flag option, but -i (or --nonBlind) instead

Hi, I have solve these problems. thank you.
But there's a new error.
the command line is **/bin/Rscript ./pipe4C.R --vpFile=./example/VPinfo.txt --fqFolder=./example --outFolder=./outF/ --cores 8 --plot –wig**
**------ Loading functions and configuration file
Error in if (argsL$plot) { : missing value where TRUE/FALSE needed
Execution halted**

Any idea on how to resolve this problem?

**Comment by liu-555** [comment]
> I'm not behind a computer now, but I'm guessing now you don't call the script in the right way. I'm reading -wig instead of --wig ?

I'm sorry to bother you. You're wonderful! 
I correct the commend line **/bin/Rscript ./pipe4C.R --vpFile=./example/VPinfo.txt --fqFolder=./example --outFolder=./outF/ --cores 8 --plot --wig**
**----- Loading functions and configuration file
                                                       
                        i,.r rrsi;:;sir                
                      ;:;;XX5XX22A22s;2,i;.            
                   is;AA3XA3hh5A3M222Ah2Ar5i:          
                  i.rX5rM2MGsHHShM2GH2MrSh35irs        
                 ;r.2i5GhG#3@B2GhG&2hAGGh3MA22.X       
                 ,:X2XhX9H5#G#9HHMGSMhMMM2H25X3Ar      
                 Xsih2S53M##53##9M59G#GA&B335H2hii;    
                 r:2h2h###S5#G5BhM&AB#9 23&hAGsH3,s,   
                 s.2r5MsSS2&hSBhS#3&hHBM&S2#MHHA35i;.  
                 .s;rs5G23&H#5MBG3hh9h2GM9G3SGAhsAA,,  
                 : rAr52HMM3GB2hhG#55SSHMh9GMM393s5ii  
                   r.;2i3X2333MMHMAB32HrMMs323HA9hA2;, 
       ;.:r        ;:i;2X2355MA3A5MAM322Asi55hAHh35i;. 
       ;s;:;.        ::,AsiXsAssAAAXrrX;.,i;rX2Mhr3,s  
      .;ssr.;         , ,:,A ;i;Ai,;;:,  . ;i5hAG5:X:  
       si2h i,          : ,::r s,:i.; : ...,Ah2MX35;i  
       ;X;M3::;,                        ,.:2Xh5Shs5;r  
       .5rsXsr.; .                      :;X2sHh2A2::   
         rs;5r.i ;                    , ;r3Ahh2hA:s    
          Aii2Xr;: ..            .. :.3:2X5HM2Assr,    
          :;35X2irr.s:,., .. , , :r,5;r55MMiA5sA.      
            .XX32ss:r.i..: :  i.i:.Xr3MA3A5AAi,s       
             ir:X2AAs:;sr;,;rA,XX55A5A3XXX:ir,:.       
               i.3A,hh2rr25XrA2MAX52H2s;5,2.           
                 :.Xi.5;h5,3Arri;AiA; 5                
                     ; ;.,;::r ;i.; .:                 
                        , ., , ,,                      

------ Reading the VP info file: ./example/VPinfo.txt

------ Demultiplexing Fastq files based on VPinfo file
      >>> Reading Fastq:  reads_set_1_viewpoint_10_ESC_replicate_1.fastq.gz  <<<
         ### set_1_viewpoint_10_ESC_replicate_1 check for primer sequence GAGGGTAATTTTAGCCGATC spacer:0 max mismatch:0

      >>> Reading Fastq:  reads_set_1_viewpoint_10_ESC_replicate_2.fastq.gz  <<<
         ### set_1_viewpoint_10_ESC_replicate_2 check for primer sequence GAGAGGGTAATTTTAGCCGATC spacer:0 max mismatch:0

      >>> Reading Fastq:  reads_set_1_viewpoint_10_ESC_replicate_3.fastq.gz  <<<
         ### set_1_viewpoint_10_ESC_replicate_3 check for primer sequence AGGAGGGTAATTTTAGCCGATC spacer:0 max mismatch:0


------ 4Cseq analysis
   +++ experiment: set_1_viewpoint_10_ESC_replicate_1 +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:  ./outF/FASTQ/set_1_viewpoint_10_ESC_replicate_1.fastq.gz
         ### Total Reads: 1448872
      >>> Alignment of reads to reference genome <<<
         ### attempt 1
Error in system(command = CMD, intern = TRUE) : error in running command
Calls: Run.4Cpipeline -> makeBAM -> system
Execution halted**

**Comment by liu-555** [comment]
Hi, I would like to aks a question. I have installed Rsamtools , Rbowtie2 and “BSgenome.Hsapiens.UCSC.hg19 package”.
**Rscript ./pipe4C.R --vpFile=./example/VPinfo.txt --fqFolder=./example --outFolder=./outF/ --**cores 8 --plot --wig**
------ Loading functions and configuration file
                                                       
                        i,.r rrsi;:;sir                
                      ;:;;XX5XX22A22s;2,i;.            
                   is;AA3XA3hh5A3M222Ah2Ar5i:          
                  i.rX5rM2MGsHHShM2GH2MrSh35irs        
                 ;r.2i5GhG#3@B2GhG&2hAGGh3MA22.X       
                 ,:X2XhX9H5#G#9HHMGSMhMMM2H25X3Ar      
                 Xsih2S53M##53##9M59G#GA&B335H2hii;    
                 r:2h2h###S5#G5BhM&AB#9 23&hAGsH3,s,   
                 s.2r5MsSS2&hSBhS#3&hHBM&S2#MHHA35i;.  
                 .s;rs5G23&H#5MBG3hh9h2GM9G3SGAhsAA,,  
                 : rAr52HMM3GB2hhG#55SSHMh9GMM393s5ii  
                   r.;2i3X2333MMHMAB32HrMMs323HA9hA2;, 
       ;.:r        ;:i;2X2355MA3A5MAM322Asi55hAHh35i;. 
       ;s;:;.        ::,AsiXsAssAAAXrrX;.,i;rX2Mhr3,s  
      .;ssr.;         , ,:,A ;i;Ai,;;:,  . ;i5hAG5:X:  
       si2h i,          : ,::r s,:i.; : ...,Ah2MX35;i  
       ;X;M3::;,                        ,.:2Xh5Shs5;r  
       .5rsXsr.; .                      :;X2sHh2A2::   
         rs;5r.i ;                    , ;r3Ahh2hA:s    
          Aii2Xr;: ..            .. :.3:2X5HM2Assr,    
          :;35X2irr.s:,., .. , , :r,5;r55MMiA5sA.      
            .XX32ss:r.i..: :  i.i:.Xr3MA3A5AAi,s       
             ir:X2AAs:;sr;,;rA,XX55A5A3XXX:ir,:.       
               i.3A,hh2rr25XrA2MAX52H2s;5,2.           
                 :.Xi.5;h5,3Arri;AiA; 5                
                     ; ;.,;::r ;i.; .:                 
                        , ., , ,,                      

------ Reading the VP info file: ./example/VPinfo.txt

------ Demultiplexing Fastq files based on VPinfo file
      >>> Reading Fastq:  reads_set_1_viewpoint_10_ESC_replicate_1.fastq.gz  <<<
         ### set_1_viewpoint_10_ESC_replicate_1 check for primer sequence GAGGGTAATTTTAGCCGATC spacer:0 max mismatch:0

      >>> Reading Fastq:  reads_set_1_viewpoint_10_ESC_replicate_2.fastq.gz  <<<
         ### set_1_viewpoint_10_ESC_replicate_2 check for primer sequence GAGAGGGTAATTTTAGCCGATC spacer:0 max mismatch:0

      >>> Reading Fastq:  reads_set_1_viewpoint_10_ESC_replicate_3.fastq.gz  <<<
         ### set_1_viewpoint_10_ESC_replicate_3 check for primer sequence AGGAGGGTAATTTTAGCCGATC spacer:0 max mismatch:0


------ 4Cseq analysis
   +++ experiment: set_1_viewpoint_10_ESC_replicate_1 +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:  ./outF/FASTQ/set_1_viewpoint_10_ESC_replicate_1.fastq.gz
         ### Total Reads: 1448872
      >>> Alignment of reads to reference genome <<<
         ### attempt 1
open: No such file or directory
[bam_index_build2] fail to open the BAM file.
          sh: bowtie2: command not found
          sort: invalid option -- 'T'
          open: No such file or directory
          [bam_sort_core] fail to open file /tmp/Rtmpg44ZQj/aln.1b17b6ff2eaa0
          [samopen] no @SQ lines in the header.
          [sam_read1] missing header? Abort!
Error in value[[3L]](cond) : 
  failed to open BamFile: file(s) do not exist:
  './outF/BAM/set_1_viewpoint_10_ESC_replicate_1.bam'
Calls: Run.4Cpipeline ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted**

could you give me some advice? thank you.

**Comment by geertgeeven** [comment]
I'm currently traveling, but I'll get back to you on this. It seems like Bowtie2 is not able to write either the final BAM but more likely some temporary file we use during sorting. You need to specify a folder in which Bowtie2 can write temp files.

**Comment by geertgeeven** [comment]
Also now that I am studying the error again, please make sure that you have bowtie2 installed and that the folder where the executable 'bowtie2' is located is within the PATH, i.e. the pipe4C script should be able to execute it.
