### ISSUE TITLE
NA as result

### ISSUE THREAD

**Issue by eandresleon** [deLaatLab/pipe4C#10]
Dear all,
I've downloaded your software and I've trying to reproduce the example provided. I've downloaded de mm9 fasta file from ensembl (version 67) and everything works perfectly but there is no results. I mean, the report file contains:

```
vpname nReads motifPosperc readlenperc nMapped nMappedCis nMappedCisperc fragMapped fragMappedCis fragMappedCisPerc fragMappedCisCorr fragMappedCisPercCorr nCaptures nCisCaptures topPct capt100Kb cov100Kb capt1Mb cov1Mb
set_1_viewpoint_10_ESC_replicate_1 1448872 100 100 1134817 0 0 0 0 NA 0 NA 0 0 NA 0 NA 0 NA
set_1_viewpoint_10_ESC_replicate_2 1460398 100 100 1147176 0 0 0 0 NA 0 NA 0 0 NA 0 NA 0 NA
set_1_viewpoint_10_ESC_replicate_3 2203113 100 100 945795 0 0 0 0 NA 0 NA 0 0 NA 0 NA 0 NA
```

if I also take a look to the wig file, in each coordinate I have also a NA value. Quite weird I think.

I've use the BAM files in the IGV app and I see an enormous peak (having 322191 reads) at the position chr3:34,547,525 and other smaller peaks around. I have tried to change the vppos value in the VPinfo (I guess that the mm9 I'm using is different from yours and the positions could variate), but I always obtain a NA value .... I've tried to get positions around Mccc1 and Sox2 in my mm9 just in case ... but always NA values ....

Any help is really appreciate!!

Thanks in advance

**Comment by krijgerp** [comment]
Dear Eduardo,
The BSgenome mm9 package is using the UCSC version. please make your bowtie2 index using the UCSC fasta. The problem is that UCSC uses chr1 as chrom name, and ensembl just 1. Let me know if you need more help.
Peter

**Comment by eandresleon** [comment]
No Way!!

In fact I downloaded the mm9 genome from UCSC and it worked!

Thanks for answering this dummy question

**Comment by krijgerp** [comment]
great! good luck with your experiments.

**Comment by eandresleon** [comment]
Thank you very much for your help.

I take this opportunity, if you don't mind, to ask you another question even though the issue is closed.
If I select the primer sequence in your example and do a grep -c in the fastq file, I see that 100% of the reads have that primer sequence.
If I do the same with my samples, that % is not so good, but it is close to 85%.
Now the problem comes when I run pipe4C, it tells me this:

   +++ experiment: TD1Ca +++
      >>> Trim of the fastq <<
         ### Reading Fastq: ./outF/FASTQ/TD1Ca.fastq.gz
         ### ERROR: TD1Ca - Less reads in FASTQ than set as minimum. Reads: 38

in this particular case:
>zgrep -c "CATCTCTCTATGTTCTCTGTCTTCTGCTGGA" ../data/Dauphers_5946_191002A5/T-D1-Ca_S24_R1_75nt.fastq.gz
2,823,544

any suggestion ?

Thanks in advance!

**Comment by krijgerp** [comment]
I guess you included the 4 random nts in your primer? you can use the spacer option in the vpinfo file. 
check table 3 in the README.md.

" Spacer length. Number of nt included as spacer in the primer to enable out of phase sequencing. Default = 0. The spacer sequence will not be used for demultiplexing. If the spacer sequence is used as a barcode include the sequence in the primer sequence and set the spacer length to 0"

**Comment by eandresleon** [comment]
Well, these are not my samples so I know nothing about them ... I'm just the one who's going to analyse them. 
Thanks for the spacer option!
