### ISSUE TITLE
Questions about alignment and VPinfo.txt

### ISSUE THREAD

**Issue by kalavattam** [deLaatLab/pipe4C#11]
Hi, I am working with data that was generated following your recent 4C-seq protocol published in _Methods_. I have a few questions about processing the resulting 4C-seq fastq files.

In reading over the manuscript and code, it looks like the pipeline is not set up to process forward orientation and reverse-complement orientation fastqs from paired-end sequencing, is that correct? In that case, I think it would be appropriate to run the pipeline using only the forward fastq from paired-end sequencing as a replacement for a single-end sequencing fastq.

Also, what sequence information should be entered in the primer field in VPinfo.txt? Is this the viewpoint-specific portion of the reading primer, or is this the viewpoint-specific portion of the non-reading primer?

Thanks,
Kris

**Comment by krijgerp** [comment]
Dear Kris,
Indeed just use the fastq file belonging to the reading primer (the primer binding close to the first cutter RE site).  For the vp info use the reading primer. Good luck, Peter

**Comment by kalavattam** [comment]
Thank you, Peter. Just to clarify, this should be the full reading primer sequence, including the hybridization sequence and (if applicable) spacer sequence? Or should this just be the primer sequence specific to the VP?
