### ISSUE TITLE
Processing fastq files without primer

### ISSUE THREAD

**Issue by ChanakaCooray** [deLaatLab/pipe4C#12]
Hi,

I used the tool to process the 4C fastq files mentioned below.

https://www.ncbi.nlm.nih.gov/sra?term=SRX339441

However I noticed that the primers of the reads of those fastq files has already been removed and the fastq files contain the reads without the primer sequence and the restriction enzyme sequences. How can I use this tool to process these fastq files? What should I put in the primer section of the VPinfo.txt file? 

The primer/restriction sites and position information are listed in this document.

https://static-content.springer.com/esm/art%3A10.1186%2Fgb-2013-14-11-r129/MediaObjects/13059_2013_3320_MOESM17_ESM.docx

Appreciate the help.

Thanks,
Chanaka.

**Comment by krijgerp** [comment]
This is currently not possible directly using our pipeline. Here is a (not tested) solution for your problem, let me know whether it works:

1. As all the reads start with GATC you can use GATC as primer sequence in the vpinfo file. 

2. Modify the functions.R script:

remove the following lines:
if ( motif.1st.pos < 5 ){
        motif.1st.pos.2nd <- TRUE
        #motif.1st.pos <- as.numeric( names( sort( table( gregexpr( firstcutter, sequences )[[1]][2] ), decreasing=TRUE ) )[1] )
        
        motifPos<-sort( table( gregexpr( firstcutter, sequences )[[1]][2] ), decreasing=TRUE )[1]
        motif.1st.pos<-as.numeric( names(motifPos))
        motifPos.perc<-round(as.numeric(motifPos/nReads*100),2)
        
        
      }

good luck,
Peter

**Comment by ChanakaCooray** [comment]
Hi Peter,

Thank you for quickly get back to me. But I am not sure I understand what you meant by all the reads start with GATC. Because I am seeing reads in the fastq file those does not start with GATC in the SRR957010 fastq file. 

I have a suggestion by the way, I can append the primer sequence for every read in the fastq file, does that work?

**Comment by ChanakaCooray** [comment]
Also I followed what you suggested as to put "GATC" as the primer sequence only using "SRR957009.fastq" file as all of it's reads starts with "GATC". Also I commented out the lines you mentioned as well in the functions.R file. Following is my VPinfo.txt file.

expname	primer	firstenzyme	secondenzyme	genome	vpchr	vppos	analysis	fastq
AG_A	GATC	HindIII	DpnII	genome	4	10384033	cis	SRR957009_1.fastq.gz

But I am getting following error.

`
------ Reading the VP info file: ./data/VPinfo.txt

------ Demultiplexing Fastq files based on VPinfo file
      >>> Reading Fastq:  SRR957009_1.fastq.gz  <<<
         ### AG_A check for primer sequence GATC spacer:0 max mismatch:0


------ 4Cseq analysis
   +++ experiment: AG_A +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:  ./outF/FASTQ/AG_A.fastq.gz
         ### Total Reads: 1477473
         ### ERROR: AG_A 1st RE motif not found in reads
         ### ERROR:AG_A trimmed file not found
------ Writing final report

Error in gzfile(file, "rb") : cannot open the connection
Calls: Run.4Cpipeline -> export.report -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file './outF/RDS/NA', probable reason 'No such file or directory'
Execution halted
`

Appreciate your help.

**Comment by krijgerp** [comment]
Hi,
I had a quick look at the fastq file (SRR957009.fastq.gz) using zless and the reads are starting with GATC (Dpn2). I assumed they use Dpn2 as the first cutter. However when i look at the reads in the other file SRR957010.fastq.gz they start with AAGCTT (HindIII). I am not familiour with the details of this paper, but it looks like they sequenced from both sites of the amplicon.

So I guess they only removed the primer sequence and not the restriction motif. So I guess you can still try my previous suggestion but replace GATC for AAGCTT. Or indeed ad the primer sequence to the fastq file.

**Comment by ChanakaCooray** [comment]
Hi,

Thank you for analyzing the fastq files. I also noticed the same thing.

So just to clarify again, when using SRR957009.fastq.gz file, I have use GATC as primer sequence since all the reads are starting with GATC right? In that case what should I put for the first and second enzymes?

I tried using both GATC and AAGCTT as primer sequence using only SRR957009.fastq file and commented the code as well but it got failed.

Am I doing something wrong?

### Using GATC
```
**VPinfo.txt**
expname primer  firstenzyme     secondenzyme    genome  vpchr   vppos   analysis        fastq
AG_A    GATC    HindIII DpnII   genome  4       10384033        cis     SRR957009_1.fastq.gz

**Output Log**
------ Reading the VP info file: ./data/VPinfo.txt

------ Demultiplexing Fastq files based on VPinfo file
      >>> Reading Fastq:  SRR957009_1.fastq.gz  <<<
         ### AG_A check for primer sequence GATC spacer:0 max mismatch:0


------ 4Cseq analysis
   +++ experiment: AG_A +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:  ./outF/FASTQ/AG_A.fastq.gz
         ### Total Reads: 1477473
         ### ERROR: AG_A 1st RE motif not found in reads
         ### ERROR:AG_A trimmed file not found
------ Writing final report

Error in gzfile(file, "rb") : cannot open the connection
Calls: Run.4Cpipeline -> export.report -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file './outF/RDS/NA', probable reason 'No such file or directory'
Execution halted

```
### Using AAGCTT
```
**VPinfo.txt**
expname primer  firstenzyme     secondenzyme    genome  vpchr   vppos   analysis        fastq
AG_A    AAGCTT    HindIII DpnII   genome  4       10384033        cis     SRR957009_1.fastq.gz

**Output Log**
------ Reading the VP info file: ./data/VPinfo.txt

------ Demultiplexing Fastq files based on VPinfo file
      >>> Reading Fastq:  SRR957009_1.fastq.gz  <<<
         ### AG_A check for primer sequence AAGCTT spacer:0 max mismatch:0


------ 4Cseq analysis
   +++ experiment: AG_A +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:  ./outF/FASTQ/AG_A.fastq.gz
         ### ERROR: AG_A - Less reads in FASTQ than set as minimum. Reads: 0
         ### To continue alter minAmountRead argument
         ### ERROR:AG_A trimmed file not found
------ Writing final report

Error in gzfile(file, "rb") : cannot open the connection
Calls: Run.4Cpipeline -> export.report -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file './outF/RDS/NA', probable reason 'No such file or directory'
Execution halted

```

**Comment by krijgerp** [comment]
For 4C only the read starting from your firstcutter should be used. So in your case this is HindIII. Therefore perform the demultiplexing using AAGCTT as you did above, but with the fastq file that starts with AAGCTT (so fastq  SRR957010.fastq.gz).
When I have time I will update the pipeline so it will be compatible with fastq files that are already trimmed for the primer sequence.

**Comment by ChanakaCooray** [comment]
Hi,

Thank you for clarifying. So I did put AAGCTT as the primer for SRR957010.fastq.gz file as you advised. Following is the VPinfo.txt file.

```
expname	primer	firstenzyme	secondenzyme	genome	vpchr	vppos	analysis	fastq
AG_A	AAGCTT	HindIII	DpnII	genome	4	10384033	cis	SRR957010.fastq.gz
```

It went further ahead of the pipeline but it shows another error at the end. Do you have an idea of the reason for this?

```
------ Reading the VP info file: ./data/VPinfo.txt

------ Demultiplexing Fastq files based on VPinfo file
      >>> Reading Fastq:  SRR957010.fastq.gz  <<<
         ### AG_A check for primer sequence AAGCTT spacer:0 max mismatch:0


------ 4Cseq analysis
   +++ experiment: AG_A +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:  ./outF/FASTQ/AG_A.fastq.gz
         ### Total Reads: 1774708
100
      >>> Alignment of reads to reference genome <<<
         ### attempt 1
          1774708 reads; of these:
            1774708 (100.00%) were unpaired; of these:
              29486 (1.66%) aligned 0 times
              1545742 (87.10%) aligned exactly 1 time
              199480 (11.24%) aligned >1 times
          98.34% overall alignment rate
      >>> Create frag map for genome: genome with RE1: AAGCTT and RE2: GATC and capture length:30 <<<
         ### Loading: pipe4C-master/fragFolder/genome_AAGCTT_GATC.rds
         ### Retrieve and store the unique fragends
         ### Selecting fragments from whole genome
      >>> Align reads to fragments <<<
      >>> Compute statistics and create report <<<
Error: subscript is a logical vector with out-of-bounds TRUE values
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
Execution halted
```

**Comment by krijgerp** [comment]
Could you tell me which BSgenome you are using, how you made the bowtie2 index, and which config file you are using? Peter

**Comment by ChanakaCooray** [comment]
Hi Peter,

Yes I have used the the bioconductor package as you mentioned BSgenome.Athaliana.TAIR.TAIR9 and the Bowtie2 index we used can be found in here.
```
http://bowtie-bio.sourceforge.net/bowtie2/index.shtml
The Bowtie2 index name is - A. thaliana, TAIR10
The link - https://genome-idx.s3.amazonaws.com/bt/TAIR10.zip
```

So I guess in that case we do not need to change the R script you mentioned as above right? Also you might notice in here we used TAIR10 Bowtie2 index and the bioconductor package is TAIR9. We have used that because bioconductor does not have a package for TAIR9 and they have mentioned that you can use this package for TAIR10 as well in their website.

https://bioconductor.org/packages/release/data/annotation/html/BSgenome.Athaliana.TAIR.TAIR9.html

 **Note that TAIR10 is an "annotation release" based on the same genome assembly as TAIR9.**

Also I downloaded the fastq files using fastq-dump tool. I think this information would be enough for you to reproduce this error, Let me know if you need more information, I am happy to provide.

Thank you so much for looking into this.

Thanks,
Chanaka.

**Comment by krijgerp** [comment]
Dear Chanaka,
the Bowtie2 index is made using the ensembl reference genome (so the chromosome names do not match the chromosome names used in the BSgenome package).

I guess the easiest is to first generate the fasta file using the bsgenome package:

**Comment by ChanakaCooray** [comment]
Hi Peter,

Ok got it. I will try this way and let you know the results. Thank you.

Chanaka.

**Comment by ChanakaCooray** [comment]
Hi Peter,

I followed your approach by exporting the fasta and then create bowtie2 index by myself. After using the generated bowtie2 index, I am getting the following error. Do you have any idea? Did I do something wrong?
Appreciate the help.

Chanaka.

```
------ Reading the VP info file: ./data/VPinfo.txt

------ Demultiplexing Fastq files based on VPinfo file
      >>> Reading Fastq:  SRR957010.fastq.gz  <<<
         ### AG_A check for primer sequence AAGCTT spacer:0 max mismatch:0


------ 4Cseq analysis
   +++ experiment: AG_A +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:  ./outF/FASTQ/AG_A.fastq.gz
         ### Total Reads: 1774708
100
      >>> Alignment of reads to reference genome <<<
         ### attempt 1
          1774708 reads; of these:
            1774708 (100.00%) were unpaired; of these:
              29486 (1.66%) aligned 0 times
              1545742 (87.10%) aligned exactly 1 time
              199480 (11.24%) aligned >1 times
          98.34% overall alignment rate
      >>> Create frag map for genome: TAIR9 with RE1: AAGCTT and RE2: GATC and capture length:30 <<<
         ### Creating new digest for genome : TAIR9 with re1 : AAGCTT and re2 : GATC
Loading required package: BSgenome.Athaliana.TAIR.TAIR9
Loading required package: BSgenome
Loading required package: rtracklayer
[1] "Processing Chr1"
[1] "Processing Chr2"
[1] "Processing Chr3"
[1] "Processing Chr4"
[1] "Processing Chr5"
[1] "Processing ChrM"
[1] "Processing ChrC"
         ### Retrieve and store the unique fragends
          ### Create FASTA file for capture length 30
          ### Mapping FASTA file back to TAIR9
          ### Bowtie2: 30
         ### Selecting fragments from whole genome
      >>> Align reads to fragments <<<
      >>> Compute statistics and create report <<<
Error: subscript is a logical vector with out-of-bounds TRUE values
In addition: Warning messages:
1: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
2: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
3: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
4: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
5: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
6: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
Execution halted
```

**Comment by krijgerp** [comment]
Dear Chanaka,
It seems that the person that generated the bsgenome used Chr as chromosome name instead of chr as is normally done in all bsgenomes provided by UCSC. please replace 

 CHR <- paste0("chr", vpChr[i])
for

 CHR <- paste0("Chr", vpChr[i])

and it will work. I just tested it.

good luck,Peter

**Comment by ChanakaCooray** [comment]
Hi Peter,

It worked! Thank you so much.

I have another concern if you do not mind. I tried to do the same approach for SRR957009.fastq by changing the primer as GATC. Following is my VPinfo.txt file.

```
expname	primer	firstenzyme	secondenzyme	genome	vpchr	vppos	analysis	fastq
AG_A	GATC	HindIII	DpnII	TAIR9	4	10384033	cis	SRR957009_1.fastq.gz
```

But I am getting following error. What could be the reason for this?

```

------ Loading functions and configuration file
                                                       
                        i,.r rrsi;:;sir                
                      ;:;;XX5XX22A22s;2,i;.            
                   is;AA3XA3hh5A3M222Ah2Ar5i:          
                  i.rX5rM2MGsHHShM2GH2MrSh35irs        
                 ;r.2i5GhG#3@B2GhG&2hAGGh3MA22.X       
                 ,:X2XhX9H5#G#9HHMGSMhMMM2H25X3Ar      
                 Xsih2S53M##53##9M59G#GA&B335H2hii;    
                 r:2h2h###S5#G5BhM&AB#9 23&hAGsH3,s,   
                 s.2r5MsSS2&hSBhS#3&hHBM&S2#MHHA35i;.  
                 .s;rs5G23&H#5MBG3hh9h2GM9G3SGAhsAA,,  
                 : rAr52HMM3GB2hhG#55SSHMh9GMM393s5ii  
                   r.;2i3X2333MMHMAB32HrMMs323HA9hA2;, 
       ;.:r        ;:i;2X2355MA3A5MAM322Asi55hAHh35i;. 
       ;s;:;.        ::,AsiXsAssAAAXrrX;.,i;rX2Mhr3,s  
      .;ssr.;         , ,:,A ;i;Ai,;;:,  . ;i5hAG5:X:  
       si2h i,          : ,::r s,:i.; : ...,Ah2MX35;i  
       ;X;M3::;,                        ,.:2Xh5Shs5;r  
       .5rsXsr.; .                      :;X2sHh2A2::   
         rs;5r.i ;                    , ;r3Ahh2hA:s    
          Aii2Xr;: ..            .. :.3:2X5HM2Assr,    
          :;35X2irr.s:,., .. , , :r,5;r55MMiA5sA.      
            .XX32ss:r.i..: :  i.i:.Xr3MA3A5AAi,s       
             ir:X2AAs:;sr;,;rA,XX55A5A3XXX:ir,:.       
               i.3A,hh2rr25XrA2MAX52H2s;5,2.           
                 :.Xi.5;h5,3Arri;AiA; 5                
                     ; ;.,;::r ;i.; .:                 
                        , ., , ,,                      

------ Reading the VP info file: ./data/VPinfo.txt

------ Demultiplexing Fastq files based on VPinfo file
      >>> Reading Fastq:  SRR957009_1.fastq.gz  <<<
         ### AG_A check for primer sequence GATC spacer:0 max mismatch:0


------ 4Cseq analysis
   +++ experiment: AG_A +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:  ./outF/FASTQ/AG_A.fastq.gz
         ### Total Reads: 1477473
         ### ERROR: AG_A 1st RE motif not found in reads
         ### ERROR:AG_A trimmed file not found
------ Writing final report

Error in gzfile(file, "rb") : cannot open the connection
Calls: Run.4Cpipeline -> export.report -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file './outF/RDS/NA', probable reason 'No such file or directory'
Execution halted
```

**Comment by krijgerp** [comment]
it does not make sense to map from the second cutter . You will need to map to a dpn2 digested genome in your case however because the firstcutter was hindIII, many dpn2 fragments will not be able to ligate (only the dpn2 sites closest to a hindIII site). So while you can map the reads by swapping the enzymes in your vpino file (dpn2 as the firstcutter) it does not make sense. I hope this is clear. Peter

**Comment by ChanakaCooray** [comment]
Thank you for the information Peter. Really Appreciate your help on the issue.
