### ISSUE TITLE
peakC "Error in if (data[1, 1] > vp.pos)"

### ISSUE THREAD

**Issue by YuhanTian** [deLaatLab/pipe4C#13]
Hi,
When I run `resPeakC <- doPeakC(rdsFiles = rdsFiles)`, as mentioned below, it don't work.
`
Error in if (data[1, 1] > vp.pos) { :
  missing value where TRUE/FALSE needed
`
Can you help me? Thank you so much.

**Comment by krijgerp** [comment]
Dear YuhanTian,
Make sure to use experiments that use exactly the same viewpoint. 
if this is the case I will need more information to help you. Can you share your rds files? Peter

**Comment by YuhanTian** [comment]
Thank you for quickly get back to me. I processed GSM996246.rds, GSM996247.rds and GSM996248.rds by "peakC", which have a same viewpoint and  added attachments. (https://github.com/YuhanTian/pipe4C/blob/master/) 
What I'm puzzled about is that it get the same wrong when i process only one rds file.
Look forward to your reply!

**Comment by krijgerp** [comment]
Dear YuhanTian,
did you generate the RDS files using our pipeline? I cannot open the rds files? Are you able to open the RDS files in R?
Peter

**Comment by YuhanTian** [comment]
Dear Peter,
Thank you for helping me solve the problem. I'm glad to tell you that I find what cause this error. when I run 4C data by pipe4C, I use 1 as vppos in VPinfo.txt which cause the problem above-mentioned. All in all, thank you for quickly get back to me.

**Comment by krijgerp** [comment]
thanks for the update and for identifying this bug.  Peter

**Comment by laillern** [comment]
Hello YuhanTian,
I am encountering the same error as you and I was wondering what you replaced vppos with.
I am using "1" as well, since I dont know the position of the VP. How did you find the position, to then replace the value in the VPoint info file, please?
Thank you in advance!
