### ISSUE TITLE
no mapped cis read

### ISSUE THREAD

**Issue by Nais29** [deLaatLab/pipe4C#16]
Hello,

I use pipe4C to analyse 4C data. 
I already analyze differents Fastq and I obtained plot.
But for this time, pipe4C run but when I check my plot, I don't have mapped cis reads, it's possible ? 
I'm a begginer in code, so I don't have the necessary distance...

I have sometimes a warning message, but I don't understand the problem : 

------ Reading the VP info file: /home/alenabec/4C_Analyses/pipe4C-master/4C_fastq/20210629/VPinfo.txt

------ Demultiplexing Fastq files based on VPinfo file
      >>> Reading Fastq:  PGJB2_S4_L001_R1_001.fastq.gz  <<<
         ### PGJB2 check for primer sequence CAAGCCTCGTTTTTGCCATG spacer:0 max mismatch:0

------ 4Cseq analysis
   +++ experiment: PGJB2 +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:  /WORKING_DIRECTORY/alenabec/4C/Results/20210629/FASTQ/PGJB2.fastq.gz
         ### Total Reads: 104528
      >>> Alignment of reads to reference genome <<<
         ### attempt 1
          104528 reads; of these:
            104528 (100.00%) were unpaired; of these:
              15621 (14.94%) aligned 0 times
              184 (0.18%) aligned exactly 1 time
              88723 (84.88%) aligned >1 times
          85.06% overall alignment rate
      >>> Create frag map for genome: hg19 with RE1: CATG and RE2: GTAC and capture length:60 <<<
         ### Loading: /home/alenabec/R/x86_64-conda-linux-gnu-library/3.6/BSgenome.Hsapiens.UCSC.hg19/R/hg19_CATG_GTAC.rds
         ### Retrieve and store the unique fragends
         ### Selecting fragments from whole genome
      >>> Align reads to fragments <<<
      >>> Compute statistics and create report <<<
      >>> Compute normalized 4C score per fragment <<<
      >>> Creating bins <<<
Loading required package: BSgenome.Hsapiens.UCSC.hg19
Loading required package: BSgenome
Loading required package: rtracklayer
making bins
Overlapping reads with bins
Error in `[[<-`(`*tmp*`, name, value = 0) :
  1 elements in value to replace 0 elements
Calls: Run.4Cpipeline -> make.reads.and.bins -> $<- -> $<- -> [[<- -> [[<-
In addition: Warning messages:
1: In read.table(VPinfo.file, sep = "\t", stringsAsFactors = FALSE,  :
  incomplete final line found by readTableHeader on '/home/alenabec/4C_Analyses/pipe4C-master/4C_fastq/20210629/VPinfo.txt'
2: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
Execution halted

but my VPinfo.txt is right...
Can you help me ? 

Thank you in advance !!

Nais29

**Comment by krijgerp** [comment]
Hi Nais29,
Could you please email us at delaatbioinf@hubrecht.eu. Can you send us the VPinfo you are using?
thank you,
Peter
