### ISSUE TITLE
Error Creating local 4C Plot

### ISSUE THREAD

**Issue by laillern** [deLaatLab/pipe4C#19]
Hello,

I am running your pipeline on a public dataset (GSE148176) and run into the following error which I do not know how to troubleshoot:

------ 4Cseq analysis
   +++ experiment: 4C_ACTA1_GM02164_rep1 +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:  ./outF_GSE148176/FASTQ/4C_ACTA1_GM02164_rep1.fastq.gz
         ### Total Reads: 4801495
      >>> Alignment of reads to reference genome <<<
         ### attempt 1
          4801495 reads; of these:
            4801495 (100.00%) were unpaired; of these:
              123156 (2.56%) aligned 0 times
              2734711 (56.96%) aligned exactly 1 time
              1943628 (40.48%) aligned >1 times
          97.44% overall alignment rate
          [bam_sort_core] merging from 1 files and 1 in-memory blocks...
      >>> Create frag map for genome: hg38 with RE1: GATC and RE2: CTAG and capture length:40 <<<
         ### Creating new digest for genome : hg38 with re1 : GATC and re2 : CTAG
Loading required package: BSgenome.Hsapiens.UCSC.hg38
Loading required package: BSgenome
Loading required package: rtracklayer
[1] "Processing chr1"
[1] "Processing chr2"
[1] "Processing chr3"
[1] "Processing chr4"
[1] "Processing chr5"
[1] "Processing chr6"
[1] "Processing chr7"
[1] "Processing chr8"
[1] "Processing chr9"
[1] "Processing chr10"
[1] "Processing chr11"
[1] "Processing chr12"
[1] "Processing chr13"
[1] "Processing chr14"
[1] "Processing chr15"
[1] "Processing chr16"
[1] "Processing chr17"
[1] "Processing chr18"
[1] "Processing chr19"
[1] "Processing chr20"
[1] "Processing chr21"
[1] "Processing chr22"
[1] "Processing chrX"
[1] "Processing chrY"
Saving Frag genome file as: ~/pgm/pipe4C-master/hg38_GATC_CTAG.rds
         ### Retrieve and store the unique fragends
          ### Create FASTA file for capture length 40
          ### Mapping FASTA file back to hg38
          ### Bowtie2: 40
         ### Selecting fragments from whole genome
      >>> Align reads to fragments <<<
      >>> Compute statistics and create report <<<
      >>> Compute normalized 4C score per fragment <<<
      >>> Creating local 4C Plot <<<
Error in stop_if_wrong_length(what, ans_len) : 
  'ranges' must have the length of the object to construct (1) or length
  1
Calls: Run.4Cpipeline ... createPlot -> GRanges -> new_GRanges -> stop_if_wrong_length
In addition: There were 23 warnings (use warnings() to see them)
Execution halted

Thanks in advance for your assistance, and let me know if you need further info to be able to troubleshoot.
N.

**Comment by krijgerp** [comment]
Dear Nathalie,
I am not sure what is causing this problem. Can you email use your vpinfo, fastq file and configuration file at delaatbioinf@hubrecht.eu. 
best,
Peter
