### ISSUE TITLE
If I only used one enzyme, can I still use this pipeline ?

### ISSUE THREAD

**Issue by smartgamer** [deLaatLab/pipe4C#2]
I'm trying to run pipe4C for our 4c data which only have one enzyme. But it could not generate fragment library. Is there any way to solve it?

**Comment by geertgeeven** [comment]
If you DO specify any known (motif and name specified in conf.yml) second enzyme, which is different from the enzyme you used you should be able to run the pipeline. We just use it to distinguish between "blind" and "non-blind" mostly. Whereas this info will not make sense in your case, you can just ignore it and your data will be mapped to the first enzyme restriction sites. Let's say you used DpnII (GATC) enzyme, as secondary you can just specify e.g. Csp6I (GTAC).

**Comment by smartgamer** [comment]
Thanks for your help.

I did as you suggested and I encountered another error now: 
"Error: subscript is a logical vector with out-of-bounds TRUE values".
This happens after the message ">>> Compute statistics and create report <<<"

Do you have any idea what causes this error and any solutions?

**Comment by smartgamer** [comment]
Another question: The fastq files I have are from pair end seq, thus with R1 and R2 for each sample. Should I merge R1 and R2 to one file before analysis?

**Comment by krijgerp** [comment]
We currently do not support R2 as input. In regular 4C this does not make sense as we trim the circles with the 2nd enzyme to allow efficient PCR. However in your case you could perform 2 4C analysis. So use the rv primer on the R2 reads.

**Comment by smartgamer** [comment]
Thanks for your reply!
