### ISSUE TITLE
No unique fragment ends

### ISSUE THREAD

**Issue by laillern** [deLaatLab/pipe4C#20]
Hi again,

Disclaimer: I'm totally new to 4C data analysis...!

Running pipe4C on public data set GSE144699 and hitting the following error : "No unique fragment ends found for capture length".

Do you have idea about where that can come from?

Thanks in advance!
N

------ 4Cseq analysis
   +++ experiment: mESC_Pde10a_17 +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:  ./outF_GSE144699/FASTQ/mESC_Pde10a_17.fastq.gz
         ### Total Reads: 8671579
      >>> Alignment of reads to reference genome <<<
         ### attempt 1
          8671579 reads; of these:
            8671579 (100.00%) were unpaired; of these:
              596021 (6.87%) aligned 0 times
              5985154 (69.02%) aligned exactly 1 time
              2090404 (24.11%) aligned >1 times
          93.13% overall alignment rate
          [bam_sort_core] merging from 1 files and 1 in-memory blocks...
      >>> Create frag map for genome: mm10 with RE1: GATC and RE2: GTAC and capture length:29 <<<
         ### Loading: ~/pgm/pipe4C-master/mm10_GATC_GTAC.rds
         ### Retrieve and store the unique fragends
         ### Selecting fragments from whole genome
No unique fragment ends found for capture length:29
         ### Skipping experiment.
         ### ERROR: mESC_Pde10a_17 No unique fragment ends found for capture length.

**Comment by krijgerp** [comment]
Hi Nathalie,
are you using the same reference genome for the bowtie2 index as is being used in the bsgenome package you are using (so UCSC instead of ensembl in case of the mm10 bsgenome package)? 

best, Peter

**Comment by laillern** [comment]
Hi Peter,
Thanks for your quick reply!

I installed this BSgenome:
 BiocManager::install("BSgenome.Mmusculus.UCSC.mm10")

I downloaded the UCSC mm10 bowtie2 index from this page:
https://benlangmead.github.io/aws-indexes/bowtie (https://genome-idx.s3.amazonaws.com/bt/mm10.zip)

I also tried to create my own index starting from the mm10 fasta file but bowtie2 wouldnt create the .rev files, so that's why I downloaded an existing one.

Thanks!

**Comment by laillern** [comment]
Hi Peter,

It's a good thing you had the booster shot so you weren't sick at the same
time as you kids!

I'm retaking the mm10 issue in this email chain for clarity.
Please find attached the VP-info file as well as the conf file, an example
of FASTQ and my bowtie2 mm10 index.

The log I get is the following:

------ Reading the VP info file: ./GSE144699_VPinfo_light.txt

------ Demultiplexing Fastq files based on VPinfo file
      >>> Reading Fastq:  SRR11007010_pass.fastq.gz  <<<
         ### Q140HOM_6M_F_Msh2_17 check for primer sequence GATC spacer:0
max mismatch:0


------ 4Cseq analysis
   +++ experiment: Q140HOM_6M_F_Msh2_17 +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:
 ./outF_GSE144699-light/FASTQ/Q140HOM_6M_F_Msh2_17.fastq.gz
         ### Total Reads: 4071263
      >>> Alignment of reads to reference genome <<<
         ### attempt 1
          4071263 reads; of these:
            4071263 (100.00%) were unpaired; of these:
              274599 (6.74%) aligned 0 times
              2827019 (69.44%) aligned exactly 1 time
              969645 (23.82%) aligned >1 times
          93.26% overall alignment rate
      >>> Create frag map for genome: mm10 with RE1: GATC and RE2: GTAC and
capture length:28 <<<
         ### Loading: ~/pgm/pipe4C-master/mm10_GATC_GTAC.rds
         ### Retrieve and store the unique fragends
         ### Selecting fragments from whole genome
No unique fragment ends found for capture length:28
         ### Skipping experiment.
         ### ERROR: Q140HOM_6M_F_Msh2_17 No unique fragment ends found for
capture length.
------ Writing final report


Thanks again for your time!

Nathalie

 mm10.tar.gz
<https://drive.google.com/file/d/1VqaZi2J-859IraY_DLV-A5nFRaiag9Wu/view?usp=drive_web>
 conf.yml
<https://drive.google.com/file/d/1gODqO4v-4Syt9CnR_I0xYkw_AwNv-4ZN/view?usp=drive_web>
 GSE144699_VPinfo_light.txt
<https://drive.google.com/file/d/1QgpUZqWtPP8B2CUFJ8iyLt_ANfc_-9r-/view?usp=drive_web>
 Q140HOM_6M_F_Msh2_17.fastq.gz
<https://drive.google.com/file/d/1ZQQx2fdPIQ1EKgB2hwd9A9qEMcVR6yuL/view?usp=drive_web>

**Comment by krijgerp** [comment]
Fixed by removing the previously generated fragGenome. The fragGenome can get corrupted when 2 processed at the same time are trying to write into this file.
