### ISSUE TITLE
pipe4C for paired-end sequencing

### ISSUE THREAD

**Issue by ccmeth** [deLaatLab/pipe4C#24]
Hi,

Thanks a lot for providing such a useful tool for analyzing 4C data. One question confused me is that my 4-C data is based on paired-end sequencing, so only R1.fastq will be used for analysis?

**Comment by krijgerp** [comment]
Hi ccmeth,
yes we only use the R1 read. In 4C we trim the 3C library with a second enzyme. In most cases, only 1 fragment will be ligated to the viewpoint and performing single end sequencing should be sufficient.
best, Peter
