### ISSUE TITLE
(ERR): "/igenomes/Mus_musculus/UCSC/mm9" does not exist or is not a Bowtie 2 index

### ISSUE THREAD

**Issue by ulloaa** [deLaatLab/pipe4C#25]
Hello, I am following the tutorial but running into an error that should be easy to fix:

(ERR): "/igenomes/Mus_musculus/UCSC/mm9" does not exist or is not a Bowtie 2 index

However, I cannot figure out what the pipeline is expecting to see under that directory. The directory above does exist. If I give the pipeline a path without the "mm9" part, the pipeline inserts "mm9". Is the pipeline expecting to see the ebwt files under the path given in the yaml file?

Thanks.

**Comment by krijgerp** [comment]
Dear Ulloaa,
the pipeline expects a Bowtie2 index with as prefix mm9.

So in the config file under bowtie2 define the mm9 folder as

 bowtie2:
  -
    mm9
    /igenomes/Mus_musculus/UCSC/

An in the folder /igenomes/Mus_musculus/UCSC/ the following files should be present:
mm9.1.bt2
mm9.2.bt2
mm9.3.bt2
mm9.4.bt2
mm9.rev.1.bt2
mm9.rev.2.bt2

kind regards,
Peter

**Comment by ulloaa** [comment]
Thank you for clarifying. The pipeline is working now!
