### ISSUE TITLE
Run.4Cpipeline -> getFragMap -> getUniqueFragends -> system

### ISSUE THREAD

**Issue by yanqishi1** [deLaatLab/pipe4C#26]
------ Reading the VP info file: ./example/VPinfo.txt

------ Demultiplexing Fastq files based on VPinfo file
      ### WARNING: File ./outF/FASTQ/set_1_viewpoint_10_ESC_replicate_1.fastq.gz exists. continuing with exisiting file.
      ### WARNING: File ./outF/FASTQ/set_1_viewpoint_10_ESC_replicate_2.fastq.gz exists. continuing with exisiting file.
      ### WARNING: File ./outF/FASTQ/set_1_viewpoint_10_ESC_replicate_3.fastq.gz exists. continuing with exisiting file.

------ 4Cseq analysis
   +++ experiment: set_1_viewpoint_10_ESC_replicate_1 +++
      >>> Trim of the fastq <<<
         ### WARNING: trimmed file set_1_viewpoint_10_ESC_replicate_1 already exists, continuing with exisiting file.
      >>> Alignment of reads to reference genome <<<
         ### WARNING: set_1_viewpoint_10_ESC_replicate_1 BAM file already exist, continuing with exisiting file.
      >>> Create frag map for genome: mm9 with RE1: GATC and RE2: GTAC and capture length:35 <<<
         ### Loading: /home/kali/Downloads/pipe4C/fragFolder/mm9_GATC_GTAC.rds
         ### Retrieve and store the unique fragends
          ### Create FASTA file for capture length 35
Loading required package: BSgenome.Mmusculus.UCSC.mm9
Loading required package: BSgenome
Loading required package: rtracklayer
          ### Mapping FASTA file back to mm9
          ### Bowtie2: 35
Error in system(cmd, intern = TRUE) : error in running command
Calls: Run.4Cpipeline -> getFragMap -> getUniqueFragends -> system
Execution halted

How to solve this problem?

**Comment by krijgerp** [comment]
Dear yanqishi1,
It is not directly clear to me what is giving this error.
the pipeline is trying to determine the fragments ends that map uniquely to the genome with a capture length of 35. 
Can you send us (delaatbioinf@hubrecht.eu) the set_1_viewpoint_10_ESC_replicate_1 BAM file to see whether this was created correctly (So I know bowtie2 and samtools are not the problem). Please also send along the configuration file that you used.

best,
Peter
