### ISSUE TITLE
Error in getPeakCPeaks(resPeakC, chr = resPeakC$vpChr, min.gapwidth = min.gapwidth) :    unused argument (chr = resPeakC$vpChr)

### ISSUE THREAD

**Issue by yermek2030** [deLaatLab/pipe4C#28]
Hello,
Thank you for making such a useful program.
I encountered the following error when trying to run the last line in the manual to export the peaks to a BED file.

At first, I was getting this error, but I seem to have figured out how to handle it:
> exportPeakCPeaks(resPeakC=resPeakC,bedFile=peaksFile,name="set_1_viewpoint_10_ESC_peakC_peaks")
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file './outF/set_1_viewpoint_10_ESC_peakC_peaks.bed': No such file or directory

I simply changed the working directory to a different one:
>peaksFile <- "../../outF/set_1_viewpoint_10_ESC_peakC_peaks.bed"
(previously, it was like in the manual: "./outF/set_1_viewpoint_10_ESC_peakC_peaks.bed")

Then I got a different error as in the title of this issue:
> exportPeakCPeaks(resPeakC=resPeakC,bedFile=peaksFile,name="set_1_viewpoint_10_ESC_peakC_peaks")
Error in getPeakCPeaks(resPeakC, chr = resPeakC$vpChr, min.gapwidth = min.gapwidth) : 
  unused argument (chr = resPeakC$vpChr)

When looking at the BED files generated it seems they are not what we want - just 149bytes (?):
>nano example_set_1_viewpoint_10_ESC_peakC_peaks.bed 
browser position chr3:33547661-35547661
track name="set_1_viewpoint_10_ESC_peakC_peaks" description="peakC peaks on chr3" visibility=2 itemRgb="On"

No errors came up before that - apart from this, all the code seems to have worked. I even get all the BAM, RDS, WIG, etc files.

**Comment by krijgerp** [comment]
Should be fixed. best Peter

**Comment by yermek2030** [comment]
> Should be fixed. best Peter

Hello, Peter
Thanks for replying. Did you mean that it is fixed or you will look at it?, since it requires fixing? I have reinstalled the whole repository in R just now using
>install_github("deWitLab/peakC", force=TRUE)
but it seems the error persists.

**Comment by krijgerp** [comment]
No it is fixed :). I just tested it but works for me.
The error was in the pipe4C wrapper (which is in the functions.R file), not the peakC package. So you need to use the new function file in the pipe4C repository.

Peter

**Comment by yermek2030** [comment]
Ah, it works now. Many thanks!
