### ISSUE TITLE
Sequencing depth normalization

### ISSUE THREAD

**Issue by DakeshiKitano** [deLaatLab/pipe4C#30]
Good day,

Writing you from Astana, Kazakhstan. Appreciate your work and pipeline! I have a question regarding normalization of reads.

Do we need to adjust 'normalizeFactor' in "conf.yml" file based on the amount of reads that we obtain? We needed to make sure our data is comparable and I find confusing the way my data gets normalized.

Could you, please, elaborate on that?

Best regards,
Daulet.

**Comment by krijgerp** [comment]
Hi Daulet,
the normalizeFactor: 1000000 in the conf.yml means that the reads (the cis reads or all reads based on the analysis column in the info file) will be normalized to 1 million reads (the sum of normalized reads (excluding the top 2 fragments with the highest reads) is 1 million.

best, Peter

**Comment by DakeshiKitano** [comment]
Thanks a lot Peter,

I have another question. I am really sorry to bother you. In the attached photo, there are the contents of .tsv file generated from the pipeline.
![to_Peter_tsv_file_contents](https://github.com/deLaatLab/pipe4C/assets/108920752/97eaa781-50b1-4783-a05d-4df6e708ebf0)

There are columns, whose abbreviations I am not getting. Where can I find what those columns mean, and how are those columns produced. As far as I understand, to produce "normReads", "reads" were multiplied by "norm4C". How was the "norm4C" derived?

Best regards,
Daulet.

**Comment by krijgerp** [comment]
Hi Daulet,
have a look in :

Krijger PHL, Geeven G, Bianchi V, Hilvering CRE, de Laat W. 4C-seq from beginning to end: A detailed protocol for sample preparation and data analysis. Methods. 2019 Jul 26. pii: S1046-2023(18)30474-2. doi: 10.1016/j.ymeth.2019.07.014. https://doi.org/10.1016/j.ymeth.2019.07.014

normReads are sequence depth normalized (so the normalizeFactor of your previous question). The norm4C column is the smoothed 4C data. Default a running mean of 21 windows is used for this.

best, Peter

**Comment by DakeshiKitano** [comment]
Thank you Peter,

I have another question. We produced a GenomePlot figure of 4C-seq coverage of all chromosomes at 35 kb bins resolution (resolution was set manually in the configuration file of the pipeline). Plot of chr 19 is attached below. We would like to understand and access the numerical data that was used to generate the 4C-seq coverage plot at 35 kb bin resolution. Could you, please, help access that data?

![genomeplotfigureat35kbbinsofchr19](https://github.com/deLaatLab/pipe4C/assets/108920752/c800c472-b8b0-4bb4-bd5a-7c23f724683c)
