### ISSUE TITLE
Could Pipe4C run with other genome such as zebrafish or others?

### ISSUE THREAD

**Issue by lwf20** [deLaatLab/pipe4C#32]
hi, thanks for your pipeline.
Could pipe4c run with other species' genomes excluding mice and humans? such as zebrafish or other genomes downloaded from Ensembl?

Looking forward to your response.
Thanks!

**Comment by krijgerp** [comment]
Hi Iwf20,
yes. The pipeline however requires a bsgenome (which are mostly based on the UCSC genomes). For Zebrafish forexample you can use: https://bioconductor.org/packages/release/data/annotation/html/BSgenome.Drerio.UCSC.danRer11.html. It is also possible to generate a bsgenome from your genome of interest using R. 
best, Peter
