### ISSUE TITLE
Error when converting wig to bigwig file

### ISSUE THREAD

**Issue by ziyin96** [deLaatLab/pipe4C#35]
HI,

I ran pipe4C on my 4C-seq sequencing data and the wig file I got looks nice in IGV.
However,  when converting the wig file into bigwig using UCSC wigToBigWig, I got this error:

```
Overlap on chr10 between items starting at 3101957 and 3101992.
Please remove overlaps and try again
```

Below is the head of the wig file
```
==> 4C_14_Kcnc2_nonblind_WIN21.wig <==
browser position chr10:111270815-113270815
track type=wiggle_0 name=4C_14_Kcnc2 visibility=full autoScale=off  viewLimits=0.0:2500.0 maxHeightPixels=50:50:8 color=0,0,200  priority=10
variableStep chrom=chr10 span=100
3101530 0
3101958 0
3101993 0
3102374 0
3103262 0
3104631 0
3117463 0
```

It seems that the window centering at 3101958 overlaps with the window centering at 3101993 under 100bp window size.

**Comment by krijgerp** [comment]
Hi ziyin96, are you using the latest version of the pipeline?
As wigToBigWig requires fixed bins. I have modified the exportWig function before the use a span of 1 instead of 100.
The pipeline btw also supports the generation of bigwig files directly when running the pipeline.

best, Peter

**Comment by ziyin96** [comment]
Thanks for your quick response. Previously, I was using the v1.1 version from the realeases. Updating to the 1.1.6 version in the master branch do resolve the issue.

Best, 
Ziyin
