### ISSUE TITLE
error after  'frag map for genome' report generation step

### ISSUE THREAD

**Issue by amywebb** [deLaatLab/pipe4C#4]
I'm getting an error and I'm not sure how to troubleshoot it.  I ran through the example without any trouble and now trying with my own data. 

Could this be related to the vpPos not overlapping with a frag? I set the vpPos to the start of the gene I know is being targeted, but I'm not sure how to choose a better pos (could not find Note 15 referenced in the user guide in regards to chr and pos).

      >>> Create frag map for genome:hg38 with RE1:GATCand RE2:TTAA and capture length:118 <<<
         ### Creating new digest for genome : hg38 with re1 : GATC and re2 : TTAA
Loading required package: BSgenome.Hsapiens.UCSC.hg38
Loading required package: BSgenome
Loading required package: rtracklayer
[1] "Processing chr1"
[1] "Processing chr2"
[1] "Processing chr3"
.
.
.
[1] "Processing chr22_KI270877v1_alt"
[1] "Processing chr22_KI270878v1_alt"
[1] "Processing chr22_KI270879v1_alt"
[1] "Processing chr22_KI270928v1_alt"
[1] "Processing chrX_KI270880v1_alt"
[1] "Processing chrX_KI270881v1_alt"
[1] "Processing chrX_KI270913v1_alt"
         ### Retrieve and store the unique fragends
          ### Create FASTA file for capture length 118
          ### Mapping FASTA file back to hg38
          ### Bowtie2: 118
         ### Selecting fragments from whole genome
      >>> Align reads to fragments <<<
      >>> Compute statistics and create report <<<
Error: subscript is a logical vector with out-of-bounds TRUE values

**Comment by krijgerp** [comment]
The vppos is not important and only used to calculate some stats. Note 15 is present in the method paper but indeed not present in GitHub. Could you email us at delaatbioinf@hubrecht.eu,. So we could help you solving this problem. 
Best, Peter
