### ISSUE TITLE
Qestions about run time and Double-end sequencing

### ISSUE THREAD

**Issue by Wenbin-Wang** [deLaatLab/pipe4C#5]
Hello!
I have a question about the run time of pipe4C. When I ues 10 cores to run pipe4c, it spend more than 24 hours at ""Creating new digest for genome". Is it a normal phenomenon?
Otherwise,  is  it can be used to processing double-ended sequencing data? If it can do it, what should I do?
I am looking forward to your reply!
Thanks!

**Comment by krijgerp** [comment]
Creating the digested genome should take less than 10 minutes. Please send an email to delaatbioinf@hubrecht.eu so we can help you with this problem. Peter
