### ISSUE TITLE
read count normalization and smoothing

### ISSUE THREAD

**Issue by fiwong** [deLaatLab/pipe4C#7]
Hi, I have bedgraph count file for fragments and would like to use pipe4C for read count normalization and smoothing. Can you point to where i should start in the R function? and what should i modify if i want to combine 2 replicates to create the bigwig file? thank you so much for your help!

**Comment by krijgerp** [comment]
Dear Fiwong,
1. I would advise you to use the pipeline from beginning to end.
2. If you would like to do the normalization your self, you could use the norm4C function that is present in the functions.R file.
3. Our pipeline does not support the generation of bigwig files, but you could you the UCSC tools or the rtracklayer package in R.
good luck,
Peter
