### ISSUE TITLE
1st RE motif not found in reads

### ISSUE THREAD

**Issue by mvheetve** [deLaatLab/pipe4C#8]
Hi,

new to 4C and to pipe4C. I ran the pipeline on a single R1 Illumina file (3Gb) file to test on a laptop while waiting for a version of pipe4C on our infrastructure (4Gb memory). At the '------ 4Cseq analysis' part the process is simply 'killed', probably due to insufficient memory. So I split my fastq in 4 parts (bad practice, I know, but I'm just working out the mechanics of the pipeline). Also tried a random sample using 
`seqtk sample` 
This is the output on one of the four parts (all parts had similar output):

`(base) mvheetve@MiBook:~$ Rscript /path/pipe4C.R --vpFile=/path/VPinfo.txt --fqFolder=/path/ --outFolder=/path/ --cores 1 --plot --wig

------ Loading functions and configuration file
                                                       
                        i,.r rrsi;:;sir                
                      ;:;;XX5XX22A22s;2,i;.            
                   is;AA3XA3hh5A3M222Ah2Ar5i:          
                  i.rX5rM2MGsHHShM2GH2MrSh35irs        
                 ;r.2i5GhG#3@B2GhG&2hAGGh3MA22.X       
                 ,:X2XhX9H5#G#9HHMGSMhMMM2H25X3Ar      
                 Xsih2S53M##53##9M59G#GA&B335H2hii;    
                 r:2h2h###S5#G5BhM&AB#9 23&hAGsH3,s,   
                 s.2r5MsSS2&hSBhS#3&hHBM&S2#MHHA35i;.  
                 .s;rs5G23&H#5MBG3hh9h2GM9G3SGAhsAA,,  
                 : rAr52HMM3GB2hhG#55SSHMh9GMM393s5ii  
                   r.;2i3X2333MMHMAB32HrMMs323HA9hA2;,
       ;.:r        ;:i;2X2355MA3A5MAM322Asi55hAHh35i;.
       ;s;:;.        ::,AsiXsAssAAAXrrX;.,i;rX2Mhr3,s  
      .;ssr.;         , ,:,A ;i;Ai,;;:,  . ;i5hAG5:X:  
       si2h i,          : ,::r s,:i.; : ...,Ah2MX35;i  
       ;X;M3::;,                        ,.:2Xh5Shs5;r  
       .5rsXsr.; .                      :;X2sHh2A2::   
         rs;5r.i ;                    , ;r3Ahh2hA:s    
          Aii2Xr;: ..            .. :.3:2X5HM2Assr,    
          :;35X2irr.s:,., .. , , :r,5;r55MMiA5sA.      
            .XX32ss:r.i..: :  i.i:.Xr3MA3A5AAi,s       
             ir:X2AAs:;sr;,;rA,XX55A5A3XXX:ir,:.       
               i.3A,hh2rr25XrA2MAX52H2s;5,2.           
                 :.Xi.5;h5,3Arri;AiA; 5                
                     ; ;.,;::r ;i.; .:                 
                        , ., , ,,                      

`------ Reading the VP info file: /path/VPinfo.txt

------ Demultiplexing Fastq files based on VPinfo file
      >>> Reading Fastq:  3-Ret2_IRX1_UMI_3_R1_demultiplexed_part1.fastq  <<<
         ### Ret2_IRX1_UMI_3_cis check for primer sequence TGCCTTTCAGGTCTCTTACT spacer:0 max mismatch:0

------ 4Cseq analysis
   +++ experiment: Ret2_IRX1_UMI_3_cis +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:  /path/FASTQ/Ret2_IRX1_UMI_3_cis.fastq.gz
         ### Total Reads: 2403536
         ### WARNING:Ret2_IRX1_UMI_3_cis - Max read length in only 57.36% of the reads.
         ### ERROR: Ret2_IRX1_UMI_3_cis 1st RE motif not found in reads
         ### ERROR:Ret2_IRX1_UMI_3_cis trimmed file not found
------ Writing final report

Error in gzfile(file, "rb") : cannot open the connection
Calls: Run.4Cpipeline -> export.report -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/path/RDS/NA', probable reason 'No such file or directory'
Execution halted`

every part has 2.5 million reads, so 2403536 after trim is not bad. The problem lies, I think, with the fact that it can't find the first RE motif (DpnII). [umi4Cpackage](https://github.com/tanaylab/umi4cpackage/tree/master/R) and fastqc clearly showed an abundant amount (almost 40%) of reads containing the primer-pad-GATC sequence. This is data from a UMI-4C experiment, so using only one RE motif, and I've followed the instructions suggested in issue #2. 

Can you give me any idea of what is going on? I've had a look at functions.R, where I think the error originates from, but I couldn't figure out why it can't find the motif. 

Thanks
Mattias

**Comment by krijgerp** [comment]
Hi mattias,
1. Are you able to run the example on our github page?
2. Can you send your vpinfo file and 1 of the fastq files so I can have a
look why the first restriction site is not found in your reads.

Peter

Op di 12 mei 2020 16:54 schreef mvheetve <notifications@github.com>:

**Comment by mvheetve** [comment]
Hej Peter, 

thanks for the quick response. 
1. The example runs smoothly up to >>>Alignment of reads to ref genome<<< as is to be expected. I haven't put in the the work to provide a mm genome nor Bowtie2 index as we currently don't have any mouse experiments, so I get the error that 'mm9 does not exist or is not a Bowtie 2 index'. For >>>Trim of the fastq<<< I get 1448872 reads total. I'll implement the genome and index and try again in the meantime to see if any other issues pop-up. 
2. For the VP_info and the R1 file of the above mentioned sample please check [here](https://wetransfer.com/downloads/1fae881385ab37aed7d8d94ed0224fed20200513070455/18b2d445d57b55de0a40bb3ccd6b204220200513070514/cb1712). 

Kind regards
Mattias

**Comment by mvheetve** [comment]
Hi,

just a quick update. Running the example ends in 'bowtie2-align exited with value 137' so also here out of memory... Maybe I should just wait for the installation and run it on a node instead. 

Mattias

**Comment by krijgerp** [comment]
I had a quick look at your data. There are 8498021 read that start with your primer, however, in most reads (5061215) the GATC site is not present. Our pipeline assumes that most reads in a 4C-seq experiment are on target at extracts the most occurring GATC position. In your case this is a non-existing position. There are 1998281 reads that have the GATC at position 30, in the hg19 genome TGCCTTTCAGGTCTCTTACTATCGAAAAAGATC this is your read.

You could just add the padding sequence and GATC site in your vpinfo file, to only extract the reads of interest.

**Comment by krijgerp** [comment]
Also It is good to realize that we have never analyzed UMI4C data using our pipeline. It is probably better to use the pipeline from the Tanay lab for this.

**Comment by WanyingX** [comment]
> 



> I had a quick look at your data. There are 8498021 reads that start with your primer, however, in most reads (5061215) the GATC site is not present. Our pipeline assumes that most reads in a 4C-seq experiment are on target and extracts the most occurring GATC position. In your case this is a non-existing position. There are 1998281 reads that have the GATC at position 30, in the hg19 genome TGCCTTTCAGGTCTCTTACTATCGAAAAAGATC this is indeed the expected position.
> 
> You could just add the padding sequence and GATC site in your vpinfo file, to only extract the reads of interest.

Hi Krijgerp, I also got same issue. But not fully understand how to add padding sequence to VP file

**Comment by krijgerp** [comment]
Hi Wanying Xu,
Just extend the primer sequence until the first restriction motif.
Best, Peter
