### ISSUE TITLE
Error in gzfile(file, mode) : cannot open the connection

### ISSUE THREAD

**Issue by celinasjose** [deLaatLab/pipe4C#9]
Hi!

I am analysing a 4C experiment using pipe4C and encountered a problem:

------ 4Cseq analysis
   +++ experiment: MKN74_iCRE11_R2 +++
      >>> Trim of the fastq <<<
         ### Reading Fastq:  ~/pipe4C-master/MKN74_iCRE11_R2_pipe4C/FASTQ/MKN74_iCRE11_R2.fastq.gz
         ### Total Reads: 52174155
      >>> Alignment of reads to reference genome <<<
         ### attempt 1
          (ERR): "/data2/repository/genome/hg38/Bowtie2Index/hg38" does not exist or is not a Bowtie 2 index
          Exiting now ...
[samopen] no @SQ lines in the header.
      >>> Create frag map for genome: hg38 with RE1: GATC and RE2: GTAC and capture length:132 <<<
         ### Creating new digest for genome : hg38 with re1 : GATC and re2 : GTAC
Loading required package: BSgenome.Hsapiens.UCSC.hg38
Loading required package: BSgenome
Loading required package: rtracklayer
[1] "Processing chr1"
[1] "Processing chr2"
[1] "Processing chr3"
[1] "Processing chr4"

.
.
.
.

[1] "Processing chr22_KQ759762v1_fix"
[1] "Processing chrY_KN196487v1_fix"
[1] "Processing chrY_KZ208923v1_fix"
[1] "Processing chrY_KZ208924v1_fix"
Error in gzfile(file, mode) : cannot open the connection
Calls: Run.4Cpipeline -> getFragMap -> Digest -> saveRDS -> gzfile
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted

Can you help me solve this issue?

Thank you in advance for your help.
Celina

**Comment by krijgerp** [comment]
Hi Celina,
it seems like you did not modify the configuration file (conf.yml). It is trying to load the Bowtie2 index for hg38 from /data2/repository/genome/hg38/Bowtie2Index/hg38. You need to replace this for the location on your computer as described in the README.md file. Let me know if you need more help.

Peter

**Comment by celinasjose** [comment]
Hi Peter,
thank you for your fast response.
I changed the diretory on the configuration file of the Bowtie2 index for hg38 and the error was solved.
However, I encountered another error:

[1] "Processing chr22_KQ759762v1_fix"
[1] "Processing chrY_KN196487v1_fix"
[1] "Processing chrY_KZ208923v1_fix"
[1] "Processing chrY_KZ208924v1_fix"
         ### Retrieve and store the unique fragends
          ### Create FASTA file for capture length 132
          ### Mapping FASTA file back to hg38
          ### Bowtie2: 132
         ### Selecting fragments from whole genome
      >>> Align reads to fragments <<<
Error in `[[<-`(`*tmp*`, name, value = 0) :
  1 elements in value to replace 0 elements
Calls: Run.4Cpipeline -> alignToFragends -> $<- -> $<- -> [[<- -> [[<-
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted

Can you help me solve this issue?

Thanks,
Celina

**Comment by krijgerp** [comment]
Dear Celine,
Could you please send the log files generated by the pipeline and the conf.yml file that you are using to delaatbioinf@hubrecht.eu. Did you have a look at whether a bam file was generated? The pipeline stopped at the moment where it overlaps the reads in the bamfile with the restriction fragments.

**Comment by eandresleon** [comment]
> Hi Peter,
> thank you for your fast response.
> I changed the diretory on the configuration file of the Bowtie2 index for hg38 and the error was solved.
> However, I encountered another error:
> 
> [1] "Processing chr22_KQ759762v1_fix"
> [1] "Processing chrY_KN196487v1_fix"
> [1] "Processing chrY_KZ208923v1_fix"
> [1] "Processing chrY_KZ208924v1_fix"
> ### Retrieve and store the unique fragends
> ### Create FASTA file for capture length 132
> ### Mapping FASTA file back to hg38
> ### Bowtie2: 132
> ### Selecting fragments from whole genome
> >>> Align reads to fragments <<<
> Error in `[[<-`(`*tmp*`, name, value = 0) :
> 1 elements in value to replace 0 elements
> Calls: Run.4Cpipeline -> alignToFragends -> $<- -> $<- -> [[<- -> [[<-
> In addition: There were 50 or more warnings (use warnings() to see the first 50)
> Execution halted
> 
> Can you help me solve this issue?
> 
> Thanks,
> Celina

May be I'm late but I also had this issue and the problem as the fragFolder value in the conf.yml
